In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(digits.data,digits.target,test_size=0.3)

## Logistic Regression

In [5]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9592592592592593

## SVM

In [6]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

## Random Forest Classifier

In [7]:
rfc=RandomForestClassifier(n_estimators=40)
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9740740740740741

## KFOLD cross validation

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [18]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
scores_logistic=[]
scores_svm=[]
scores_rfc=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(max_iter=1000),X_train,X_test,y_train,y_test))
    scores_rfc.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))


In [19]:
scores_logistic

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [20]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [21]:
scores_rfc

[0.9348914858096828, 0.9549248747913188, 0.9315525876460768]

## Cross validation using cross_val_score function

In [22]:
from sklearn.model_selection import cross_val_score


In [24]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [25]:
cross_val_score(SVC(max_iter=1000),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [26]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.91944444, 0.90555556, 0.9637883 , 0.95543175, 0.93871866])